language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit

install:
  - composer install

after_script:
  - php vendor/bin/coveralls